HarvestHub/urls.py
from django.urls import path
from . import views
 
urlpatterns= [
    path('', views.test, name="test"),
    
    path('verify_otp', views.verify_otp_view, name="verify_otp"),
    path('generate_pdf_report', views.generate_pdf_report, name="generate_pdf_report"),
    path('farmer_summary', views.farmer_summary, name="farmer_summary"),
    path('weather_report', views.weather_report, name="weather_report"),
    path('register', views.register_farmer, name='register'),
    path('login', views.login_view, name='login'),
    path('logout', views.logout_page, name='logout'),
    path('manager_dashboard', views.farmer_manager_dashboard, name='manager_dashboard'),
    path('collection', views.collection, name="collection"),
    path('collection/<str:name>', views.collectionsview, name="collection"),
    path('collection/<str:cname>/<str:pname>', views.product_details, name="product_details"),
    path('cart', views.cart_page, name="cart"),
    path('remove_cart/<str:cid>', views.remove_cart, name="remove_cart"),
    path('addtocart', views.add_to_cart, name="addtocart"),
    path('favorite', views.favorite_page, name="favorite"),
    path('favorite_viewpage', views.favorite_viewpage, name="favorite_viewpage"),
    path('remove_favorite/<str:fid>', views.remove_favorite, name="remove_favorite"),
    path('sale', views.sales_view, name="sale"),
    path('sale_product_price', views.sale_product_price_view, name="sale_product_price"),
    path('add_sale_product_price', views.add_sale_product_price_view, name="add_sale_product_price"),
    path('update_sale_product_price', views.update_sale_product_price_view, name="update_sale_product_price"),
    path('delete_sale_product_price/<int:id>', views.delete_sale_product_price_view, name="delete_sale_product_price"),
    path('show_sales_farmer_request', views.show_sales_farmer_request_view, name="show_sales_farmer_request"),
    path('approve_sales_farmer_request/<int:id>', views.approve_sales_farmer_request_view, name="approve_sales_farmer_request"),
    path('delete_sales_farmer_request/<int:id>', views.delete_sales_farmer_request_view, name="delete_sales_farmer_request"),
    path('show_farmer_detail', views.show_farmer_detail_view, name="show_farmer_detail"),
    path('delete_farmer_detail/<int:id>', views.delete_farmer_detail, name="delete_farmer_detail"),

    path('test', views.test, name="test"),
    path('search', views.search, name="search"),
]

Inventory/urls.py
from django.urls import path
from django.contrib import admin
from . import views
 
urlpatterns= [
    path('', views.home, name='home'),
    path('view', views.index, name='index'),
    path('inventory', views.inventory, name='inventory'),
    path('addnew', views.addnew, name='addnew'),
    path('edit/<int:id>', views.edit, name='edit'),
    path('update/<int:id>', views.update, name='update'),
    path('delete/<int:id>', views.destroy, name='destroy'),
]

Project/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('HarvestHub.urls')),
    
    path('customer/',include('customers.urls')),
    path('Inventory/',include('Inventory.urls')),
    path('Employee/',include('Employee.urls')),
    path('payment/',include('payment.urls')),
]

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

HarvestHub/models.py
from django.contrib.auth.models import AbstractUser, Group, Permission
from django.core.exceptions import ValidationError
from django.db import models
from django.utils import timezone
import os
from django.contrib import admin
from django.contrib.auth.admin import UserAdmin


def create_image_name(instance, filename):
    now_time = timezone.now().strftime("%Y%m%d%H%M%S")
    base_filename, file_extension = os.path.splitext(filename)
    new_filename = f"{now_time}_{base_filename}{file_extension}"
    return os.path.join(new_filename)

                
class Farmer(AbstractUser):
    groups = models.ManyToManyField(
        Group,
        verbose_name=('groups'),
        blank=True,
        related_name='farmer_groups'
    )
    user_permissions = models.ManyToManyField(
        Permission,
        verbose_name=('user permissions'),
        blank=True,
        related_name='farmer_permissions'
    )

    GENDER_CHOICES = [
        ('M', 'Male'),
        ('F', 'Female'),
        ('O', 'Other')
    ]
    
    Image = models.ImageField(upload_to=create_image_name, null=True, blank=True)
    phone_number = models.CharField(max_length=15, null=False, blank=False)
    city = models.CharField(max_length=255, null=False, blank=False)
    gender = models.CharField(max_length=1, null=False, blank=False)
    is_farmer = models.BooleanField(default=True)

        
    class Meta:
        verbose_name_plural = 'Farmer'
        

class FarmerAdmin(UserAdmin):
    model = Farmer
    fieldsets = (
        (None, {'fields': ('username', 'password',)}),
        ('Personal Info', {'fields': ('first_name', 'last_name', 'email', 'phone_number', 'date_of_birth', 'city', 'gender', 'Image')}),
        ('Permissions', {'fields': ('is_active', 'is_staff', 'is_superuser', 'groups', 'user_permissions', 'is_farmer')}),
        ('Important dates', {'fields': ('last_login', 'date_joined')}),
    )
    list_display = ('username', 'email', 'is_farmer')
    search_fields = ('username', 'email', 'first_name', 'last_name')
    filter_horizontal = ('groups', 'user_permissions')


class FarmerManager(AbstractUser):
    groups = models.ManyToManyField(
        Group,
        verbose_name=('groups'),
        blank=True,
        related_name='farmerManager_groups'
    )
    user_permissions = models.ManyToManyField(
        Permission,
        verbose_name=('user permissions'),
        blank=True,
        related_name='farmerManager_permissions'
    )
    
    is_farmer_manager = models.BooleanField(default=True)
    
    class Meta:
        verbose_name_plural = 'Farmer Manager'

    
class FarmerManagerAdmin(UserAdmin):
    model = FarmerManager
    fieldsets = (
        (None, {'fields': ('username', 'password')}),
        ('Personal Info', {'fields': ('first_name', 'last_name', 'email')}),
        ('Permissions', {'fields': ('is_active', 'is_staff', 'is_superuser',
                                    'groups', 'user_permissions', 'is_farmer_manager')}),
        ('Important dates', {'fields': ('last_login', 'date_joined')}),
    )
    list_display = ('username', 'email', 'is_farmer_manager')
    search_fields = ('username', 'email', 'first_name', 'last_name')
    filter_horizontal = ('groups', 'user_permissions')

   
class Catagory(models.Model):
    name = models.CharField(max_length=150,null=False,blank=False)
    image=models.ImageField(upload_to=create_image_name,null=True,blank=True)
    description=models.TextField(max_length=500,null=False,blank=False)
    status=models.BooleanField(default=False,help_text="0-show,1-Hidden")
    created_at=models.DateTimeField(auto_now_add=True)

    def __str__(self) :
        return self.name


class Product(models.Model):
    category = models.ForeignKey(Catagory,on_delete=models.CASCADE)
    name = models.CharField(max_length=150,null=False,blank=False)
    product_image = models.ImageField(upload_to=create_image_name,null=True,blank=True)
    quantity = models.IntegerField(null=False,blank=False)
    price = models.FloatField(null=False,blank=False)
    description = models.TextField(max_length=500,null=False,blank=False)
    status = models.BooleanField(default=False,help_text="0-show,1-Hidden")
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self) :
        return self.name
    
    
class Cart(models.Model):
    user = models.ForeignKey(Farmer,on_delete=models.CASCADE)
    product = models.ForeignKey(Product,on_delete=models.CASCADE)
    product_qty = models.IntegerField(null=False,blank=False)
    created_at = models.DateTimeField(auto_now_add=True)
    
    @property
    def total_cost(self):
        return self.product_qty * self.product.price
 
 
class Favourite(models.Model):
	user = models.ForeignKey(Farmer,on_delete=models.CASCADE)
	product = models.ForeignKey(Product,on_delete=models.CASCADE)
	created_at = models.DateTimeField(auto_now_add=True)
 
 
class Sales(models.Model):
    user = models.CharField(max_length=150,null=False,blank=False)
    name = models.CharField(max_length=150,null=False,blank=False)
    quantity = models.FloatField(null=False,blank=False)
    total_amount = models.FloatField(null=False,blank=False)
    created_at = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=20, null=False, blank=False, default='Process')
    
    
class SalesProductPrice(models.Model):
    name = models.CharField(max_length=150,null=False,blank=False)
    price = models.FloatField(null=False,blank=False)
    created_at = models.DateField(default=timezone.now)

Inventory/models.py
from django.db import models
 
class Inventory(models.Model):
    cropName = models.CharField(max_length=100)
    cropType = models.CharField(max_length=100)
    image = models.CharField(max_length=100)
    quantity = models.CharField(max_length=100)
    expiryDate = models.CharField(max_length=100)
    supplier = models.CharField(max_length=100)
    pricePerUnit = models.CharField(max_length=100)
    status = models.CharField(max_length=100)

 

HarvestHub/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from .models import *

class FarmerRegistrationForm(UserCreationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter User Name'}))
    email = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter Email Address'}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Enter Your Password'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Enter Confirm Password'}))
    date_of_birth = forms.DateField(widget=forms.DateInput(format='%Y/%m/%d', attrs={'class': 'form-control', 'placeholder': 'YYYY/MM/DD'}))
    city = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter City'}))
    phone_number = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter Phone Number'}))

    class Meta:
        model = Farmer
        fields = ['username', 'email', 'password1', 'password2', 'gender', 'city', 'Image', 'phone_number']
        
        
class FarmerRegistrationTestForm(UserCreationForm):
    username = username = forms.CharField(
       # label='UserName',
        widget=forms.TextInput(attrs={'class': 'form-control border-primary', 'id': 'username'})
    )
    email = forms.EmailField(
        label='Email',
        widget=forms.EmailInput(attrs={'class': 'form-control border-primary', 'id': 'email'})
    )
    password1 = forms.CharField(
        label='Password',
        widget=forms.PasswordInput(attrs={'class': 'form-control border-primary', 'id': 'password1'})
    )
    password2 = forms.CharField(
        label='Password',
        widget=forms.PasswordInput(attrs={'class': 'form-control border-primary', 'id': 'password2'})
    )
    
    city = forms.CharField(
        label='City',
        widget=forms.TextInput(attrs={'class': 'form-control border-primary', 'id': 'city'})
    )
    
    phone_number = forms.CharField(
        label='Phone Number',
        widget=forms.TextInput(attrs={'class': 'form-control border-primary', 'id': 'phone'}),
        max_length=14,
        help_text='Enter your phone number in the format +94-XXXXXXXXX'
    )
    Image = forms.ImageField(
        label='File',
        widget=forms.ClearableFileInput(attrs={'class': 'border-primary', 'id': 'file'})
    )
    
    gender = forms.ChoiceField(choices=[('', 'Select The Gender'),
                                      ('Male', 'Male'),
                                      ('Female', 'Female'),
                                      ('Other', 'Other')],
                             widget=forms.Select(attrs={'class': 'form-select'}))

    class Meta:
        model = Farmer
        fields = ['username', 'email', 'password1', 'password2', 'city', 'phone_number', 'Image', 'gender']

Inventory/forms.py
from django import forms
from Inventory.models import Inventory

class InventoryForm(forms.ModelForm):
    class Meta:
        model = Inventory
        fields = ['cropName', 'cropType', 'image', 'quantity', 'expiryDate', 'supplier', 'pricePerUnit', 'status']
        widgets = {
            'cropName': forms.TextInput(attrs={'class': 'form-control', 'oninput': 'validateCropName(event)'}),
            'cropType': forms.TextInput(attrs={'class': 'form-control'}),
            'image': forms.FileInput(attrs={'class': 'form-control'}),
            'quantity': forms.TextInput(attrs={'class': 'form-control', 'oninput': 'validateQuantity(event)'}),
            'expiryDate': forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}),
            'supplier': forms.TextInput(attrs={'class': 'form-control'}),
            'pricePerUnit': forms.TextInput(attrs={'class': 'form-control'}),
            'status': forms.TextInput(attrs={'class': 'form-control'}), 
        }

Inventory/views.py
from django.shortcuts import render, redirect

from Inventory.forms import InventoryForm
from Inventory.models import Inventory

# Create your views here.

def home(request):
    return render(request, 'Inventory/test.html')

def inventory(request):
    return render(request, 'Inventory/inventory.html')


def index(request):
    inventories = Inventory.objects.all()
    return render(request, "Inventory/show.html", {'inventories': inventories})
 
def addnew(request):
    if request.method == "POST":
        form = InventoryForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('/Inventory/view')
    else:
        form = InventoryForm()
    return render(request, "Inventory/index.html", {'form': form})
 
 
def edit(request, id):
    inventory = Inventory.objects.get(id=id)
    return render(request, "Inventory/edit.html", {'inventory': inventory})
 
def update(request, id):  
    inventory = Inventory.objects.get(id=id)  
    form = InventoryForm(request.POST, request.FILES, instance = inventory)  
    print(form.is_valid())
    if form.is_valid():  
        form.save()  
        return redirect("/Inventory/view")  
    return render(request, 'Inventory/edit.html', {'inventory': inventory})
 
def destroy(request, id):  
    inventory =Inventory.objects.get(id=id)  
    inventory.delete()  
    return redirect("/Inventory/view")

HarvestHub/templates/Inventory/edit.html
{% extends "layouts/main.html" %}
 
{% block title %}Add New Inventory Records{% endblock title %}
 
{% block content %}


<div class="col-md-12">
    <form method="POST" class="post-form" action="/Inventory/update/{{inventory.id}}" enctype="multipart/form-data">  
    {% csrf_token %}  
    <br><br><br>
    <div class="container">  
        <div class="col-12">  
            <h3>Update Details</h3>  
        </div>
        <div class="mb-3">
            <label>Inventory ID:</label>  
            <input type="text" class="form-control" name="id" id="id_id" required maxlength="20" value="{{ inventory.id }}"/>    
        </div>
        <div class="mb-3">
            <label>Crop Name:</label>  
            <input type="text" class="form-control" name="cropName" id="id_cropName" required maxlength="100" value="{{ inventory.cropName }}" />  
        </div>
        <div class="mb-3">
            <label>Crop Type:</label>  
            <input type="text" class="form-control" name="cropType" id="id_cropType" required maxlength="254" value="{{ inventory.cropType }}" />  
        </div>
        <div class="mb-3">
            <label>Image:</label>  
            <input type="file" class="form-control" name="image" id="id_image" required maxlength="15" value="{{ inventory.image }}" />  
        </div>
        <div class="mb-3">
            <label>Quantity:</label>  
            <input type="text" class="form-control" name="quantity" id="id_quantity" required maxlength="15" value="{{ inventory.quantity }}" />  
        </div>
        <div class="mb-3">
            <label>Expiry Date:</label>  
            <input type="date" class="form-control" name="expiryDate" id="id_expiryDate" required maxlength="15" value="{{ inventory.expiryDate }}" />  
        </div>  
        <div class="mb-3">
            <label>Supplier:</label>  
            <input type="text" class="form-control" name="supplier" id="id_supplier" required maxlength="15" value="{{ inventory.supplier }}" />  
        </div>
        <div class="mb-3">
            <label>Price Per Unit:</label>  
            <input type="text" class="form-control" name="pricePerUnit" id="id_pricePerUnit" required maxlength="15" value="{{ inventory.pricePerUnit }}" />  
        </div>
               <div class="mb-3">
            <label>Status:</label>  
            <input type="text" class="form-control" name="status" id="id_status" required maxlength="15" value="{{ inventory.status }}" />  
        </div>
        <div class="mb-3">
            <button type="submit" class="btn btn-success btn-lg">Update</button>  
        </div>
    </div>  
    </form>  
{% endblock content %}

HarvestHub/templates/Inventory/index.html
{% extends "layouts/main.html" %}
 
{% block title %}Add New Inventory Records{% endblock title %}
 
{% block content %}
<br><br><br>
 <div class="col-md-12">
    <form method="POST" class="post-form" action="/Inventory/addnew" enctype="multipart/form-data" onsubmit="return validateForm()">
        {% csrf_token %}
        <div class="container">
            <div class="col-12">
                <h3>Enter Details</h3>
            </div>
 
        <div class="mb-3">
            <label>Crop Name:</label>
            {{form.cropName}}
        </div>
        <div class="mb-3">
            <label>Crop Type:</label>
            {{form.cropType}}
        </div>
        <div class="mb-3">
            <label>Image:</label>
            {{form.image}}
        </div>
        <div class="mb-3">
            <label>Quantity:</label>
            {{form.quantity}}
        </div>
        <div class="mb-3">
            <label>Expiry Date:</label>
            {{form.expiryDate}}
        </div>
        <div class="mb-3">
            <label>Supplier:</label>
            {{form.supplier}}
        </div>
        <div class="mb-3">
            <label>Price Per Unit:</label>
            {{form.pricePerUnit}}
        </div>
        <div class="mb-3">
            <label>Status:</label>
            {{form.status}}
        </div>
        <div class="mb-3">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
        </div>
        </form>
 </div>
 
 {% endblock content %}

{% block scripts %}
   <script>
    function validateForm() {
        var cropName = document.querySelector('.post-form input[name="cropName"]').value.trim();
        var cropType = document.querySelector('.post-form input[name="cropType"]').value.trim();
        var quantity = document.querySelector('.post-form input[name="quantity"]').value.trim();
        var expiryDate = document.querySelector('.post-form input[name="expiryDate"]').value.trim();
        var supplier = document.querySelector('.post-form input[name="supplier"]').value.trim();
        var pricePerUnit = document.querySelector('.post-form input[name="pricePerUnit"]').value.trim();
        var status = document.querySelector('.post-form input[name="status"]').value.trim();

        var lettersOnly = /^[A-Za-z]+$/;
        var numbersOnly = /^[0-9]+$/;

        if (!cropName.match(lettersOnly)) {
            alert('Crop Name should contain only letters.');
            return false;
        }

        if (!cropType.match(lettersOnly)) {
            alert('Crop Type should contain only letters.');
            return false;
        }

        if (!quantity.match(numbersOnly)) {
            alert('Quantity should contain only numbers.');
            return false;
        }

        if (!supplier.match(lettersOnly)) {
            alert('supplier should contain only letters.');
            return false;
        }

        if (!pricePerUnit.match(numbersOnly)) {
            alert('pricePerUnit should contain only numbers.');
            return false;
        }

        if (!status.match(lettersOnly)) {
            alert('status should contain only letters.');
            return false;
        }



        // Additional validation logic can be added here if needed

        return true;
    }
</script>
{% endblock scripts %}

HarvestHub/templates/Inventory/show.html
{% extends "layouts/main.html" %}
 
{% block title %} Inventory Records{% endblock title %}

 
{% block content %}
<br>
<br>
<br>

 <div class="col-md-12">
    <span><a href="/Inventory/addnew" class="btn btn-primary">Add New Record</a></span>
      

    <div class="table-responsive">
      <table id="bootstrapdatatable" class="table table-striped table-bordered" width="100%">
         <thead>
            <th><input type="checkbox" id="checkall" /></th>
            <th>ID</th>
            <th>Crop Name</th>
            <th>Crop Type</th>
            <th>Image</th>
            <th>Quantity</th>
            <th>Expiry Date</th>
            <th>Supplier</th>
            <th>pricePerUnit</th>
            <th>Status</th>
            <th>Edit</th>
            <th>Delete</th>
         </thead>
         <tbody>
            {% for inventory in inventories %}
            <tr>
               <td><input type="checkbox" class="checkthis"></td>
               <td>{{inventory.id}}</td>
               <td>{{inventory.cropName}}</td>
               <td>{{inventory.cropType}}</td>
               <td>{{inventory.image}}</td>
               <td>{{inventory.quantity}}</td>
               <td>{{inventory.expiryDate}}</td>
               <td>{{inventory.supplier}}</td>
               <td>{{inventory.pricePerUnit}}</td>
               <td>{{inventory.status}}</td>
               <td><a href="/Inventory/edit/{{ inventory.id }}" class="btn btn-primary">Edit</a></td>
               <td><a href="/Inventory/delete/{{ inventory.id }}" class="btn btn-danger">Delete</a></td>
            </tr>
            {% endfor %}
         </tbody>
      </table>
    </div>
 </div>
 
 {% endblock content %}
 {% block scripts %}
 <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>
    <script src = "https://cdn.datatables.net/1.12.0/js/jquery.dataTables.min.js"></script>
    <script>
    $(document).ready(function() {
        $('#bootstrapdatatable').DataTable({     
          "aLengthMenu": [[3, 5, 10, 25, -1], [3, 5, 10, 25, "All"]],
            "iDisplayLength": 3
           } 
        );
    } );
   </script>
 {% endblock scripts %}
 

HarvestHub/templates/Inventory/test.html
{% extends 'layouts/main.html' %}
{% load static %}
{% block head%}
    <link rel="stylesheet" href="{% static 'CSS/weather_report.css' %}">
{% endblock head%}
{% block title %}
    Test
{% endblock title %}
{% block content %}



{% endblock content %}